export interface HistoryEntry {
  timestamp: string;
  status: 'up' | 'down' | 'degraded';
  code: number;
  responseTime: number;
}

export interface Incident {
  id: string;
  title: string;
  service: string;
  status: 'resolved' | 'investigating' | 'identified' | 'monitoring';
  severity: 'minor' | 'major' | 'critical';
  createdAt: string;
  resolvedAt?: string;
  updates: {
    timestamp: string;
    status: string;
    message: string;
  }[];
}

export interface History {
  api?: HistoryEntry[];
  dashboard?: HistoryEntry[];
  website?: HistoryEntry[];
  'auth-service'?: HistoryEntry[];
  incidents?: Incident[];
  [key: string]: HistoryEntry[] | Incident[] | undefined;
}

// Default empty history (no mock data)
function generateEmptyHistory(): History {
  return {
    'api': [],
    'dashboard': [],
    'website': [],
    'auth-service': [],
    incidents: [],
  };
}

export async function getHistory(): Promise<History> {
  // Read from history/history.json (generated by check-status.js)
  try {
    const historyData = await import('../../history/history.json');
    return historyData as unknown as History;
  } catch {
    // Return empty history if file doesn't exist
    return generateEmptyHistory();
  }
}
